//! Autogenerated weights for `pallet_social_app_registry`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-04-21, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `surfers-MacBook-Pro-2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/stack-template-runtime/stack_template_runtime.compact.compressed.wasm
// --pallet
// pallet_social_app_registry
// --extrinsic ""
// --steps 20
// --repeat 10
// --output target/benchmarks/pallet_social_app_registry.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame::{deps::frame_support::weights::constants::RocksDbWeight, prelude::*};
use core::marker::PhantomData;

/// Weight functions needed for pallet_social_app_registry.
pub trait WeightInfo {
	/// Weight of `register_app` as a function of the metadata length
	/// in bytes. Matches the `Linear<0, MaxMetadataLen>` component in
	/// the benchmark.
	fn register_app(m: u32) -> Weight;
	fn deregister_app() -> Weight;
	fn act_as_moderator() -> Weight;
}

/// Weights for `pallet_social_app_registry` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `SocialAppRegistry::NextAppId` (r:1 w:1)
	/// Storage: `SocialAppRegistry::AppsByOwner` (r:1 w:1)
	/// Storage: `SocialAppRegistry::Apps` (r:0 w:1)
	/// The range of component `m` is `[0, T::MaxMetadataLen::get()]`.
	fn register_app(m: u32) -> Weight {
		// Measured: `76`  Estimated: `3554`  Min time: 25_000_000 ps.
		// Per-byte slope: ~281 ps (dominated by SCALE encoding).
		Weight::from_parts(26_546_457, 0)
			.saturating_add(Weight::from_parts(0, 3554))
			.saturating_add(Weight::from_parts(281, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `SocialAppRegistry::Apps` (r:1 w:1)
	/// Storage: `SocialAppRegistry::AppsByOwner` (r:1 w:1)
	fn deregister_app() -> Weight {
		// Measured: `391`  Estimated: `3653`  Min time: 18_000_000 ps.
		Weight::from_parts(19_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3653))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `SocialAppRegistry::Apps` (r:1 w:0)
	fn act_as_moderator() -> Weight {
		// Measured: `349`  Estimated: `3653`  Min time: 8_000_000 ps.
		Weight::from_parts(9_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3653))
			.saturating_add(T::DbWeight::get().reads(1))
	}
}

/// For backwards compatibility and tests.
impl WeightInfo for () {
	fn register_app(m: u32) -> Weight {
		Weight::from_parts(26_546_457, 0)
			.saturating_add(Weight::from_parts(0, 3554))
			.saturating_add(Weight::from_parts(281, 0).saturating_mul(m.into()))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	fn deregister_app() -> Weight {
		Weight::from_parts(19_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3653))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn act_as_moderator() -> Weight {
		Weight::from_parts(9_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3653))
			.saturating_add(RocksDbWeight::get().reads(1))
	}
}
