//! Autogenerated weights for pallet_social_app_registry
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-04-14
//!
//! **NOTE**: These weights are placeholder estimates. Run benchmarks on your own hardware for
//! accurate production values.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame::{deps::frame_support::weights::constants::RocksDbWeight, prelude::*};
use core::marker::PhantomData;

/// Weight functions needed for pallet_social_app_registry.
pub trait WeightInfo {
	fn register_app() -> Weight;
	fn deregister_app() -> Weight;
}

/// Weights for pallet_social_app_registry using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `SocialAppRegistry::Apps` (r:0 w:1)
	/// Storage: `SocialAppRegistry::NextAppId` (r:1 w:1)
	/// Storage: `SocialAppRegistry::AppsByOwner` (r:1 w:1)
	fn register_app() -> Weight {
		Weight::from_parts(15_000_000, 1600)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}

	/// Storage: `SocialAppRegistry::Apps` (r:1 w:1)
	fn deregister_app() -> Weight {
		Weight::from_parts(12_000_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

/// For backwards compatibility and tests.
impl WeightInfo for () {
	fn register_app() -> Weight {
		Weight::from_parts(15_000_000, 1600)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}

	fn deregister_app() -> Weight {
		Weight::from_parts(12_000_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
