//! Autogenerated weights for `pallet_social_profiles`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-04-21, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `surfers-MacBook-Pro-2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/stack-template-runtime/stack_template_runtime.compact.compressed.wasm
// --pallet
// pallet_social_profiles
// --extrinsic ""
// --steps 20
// --repeat 10
// --output target/benchmarks/pallet_social_profiles.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame::{deps::frame_support::weights::constants::RocksDbWeight, prelude::*};
use core::marker::PhantomData;

/// Weight functions needed for pallet_social_profiles.
pub trait WeightInfo {
	fn create_profile() -> Weight;
	fn update_metadata() -> Weight;
	fn set_follow_fee() -> Weight;
	fn delete_profile() -> Weight;
}

/// Weights for `pallet_social_profiles` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `SocialProfiles::Profiles` (r:1 w:1)
	/// Storage: `SocialProfiles::ProfileCount` (r:1 w:1)
	fn create_profile() -> Weight {
		// Measured: `3`  Estimated: `3663`  Min time: 16_000_000 ps.
		Weight::from_parts(17_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3663))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `SocialProfiles::Profiles` (r:1 w:1)
	fn update_metadata() -> Weight {
		// Measured: `253`  Estimated: `3663`  Min time: 7_000_000 ps.
		Weight::from_parts(8_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3663))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `SocialProfiles::Profiles` (r:1 w:1)
	fn set_follow_fee() -> Weight {
		// Measured: `253`  Estimated: `3663`  Min time: 6_000_000 ps.
		Weight::from_parts(7_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3663))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `SocialProfiles::Profiles` (r:1 w:1)
	/// Storage: `SocialProfiles::ProfileCount` (r:1 w:1)
	fn delete_profile() -> Weight {
		// Measured: `131`  Estimated: `3663`  Min time: 16_000_000 ps.
		Weight::from_parts(17_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3663))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}

/// For backwards compatibility and tests.
impl WeightInfo for () {
	fn create_profile() -> Weight {
		Weight::from_parts(17_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3663))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn update_metadata() -> Weight {
		Weight::from_parts(8_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3663))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn set_follow_fee() -> Weight {
		Weight::from_parts(7_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3663))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn delete_profile() -> Weight {
		Weight::from_parts(17_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3663))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
}
