//! Autogenerated weights for pallet_social_profiles
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-04-14
//!
//! **NOTE**: These weights are placeholder estimates. Run benchmarks on your own hardware for
//! accurate production values.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame::{deps::frame_support::weights::constants::RocksDbWeight, prelude::*};
use core::marker::PhantomData;

/// Weight functions needed for pallet_social_profiles.
pub trait WeightInfo {
	fn create_profile() -> Weight;
	fn update_metadata() -> Weight;
	fn delete_profile() -> Weight;
}

/// Weights for pallet_social_profiles using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `SocialProfiles::Profiles` (r:1 w:1)
	/// Storage: `SocialProfiles::ProfileCount` (r:1 w:1)
	fn create_profile() -> Weight {
		Weight::from_parts(14_000_000, 1600)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

	/// Storage: `SocialProfiles::Profiles` (r:1 w:1)
	fn update_metadata() -> Weight {
		Weight::from_parts(11_000_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

	/// Storage: `SocialProfiles::Profiles` (r:1 w:1)
	/// Storage: `SocialProfiles::ProfileCount` (r:1 w:1)
	fn delete_profile() -> Weight {
		Weight::from_parts(13_000_000, 1489)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

/// For backwards compatibility and tests.
impl WeightInfo for () {
	fn create_profile() -> Weight {
		Weight::from_parts(14_000_000, 1600)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}

	fn update_metadata() -> Weight {
		Weight::from_parts(11_000_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}

	fn delete_profile() -> Weight {
		Weight::from_parts(13_000_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
