//! Autogenerated weights for pallet_social_profiles
//!
//! **NOTE**: These weights are placeholder estimates.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame::{deps::frame_support::weights::constants::RocksDbWeight, prelude::*};
use core::marker::PhantomData;

/// Weight functions needed for pallet_social_profiles.
pub trait WeightInfo {
	fn create_profile() -> Weight;
	fn update_metadata() -> Weight;
	fn set_follow_fee() -> Weight;
	fn delete_profile() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn create_profile() -> Weight {
		Weight::from_parts(14_000_000, 1600)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

	fn update_metadata() -> Weight {
		Weight::from_parts(11_000_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

	/// Storage: `SocialProfiles::Profiles` (r:1 w:1)
	fn set_follow_fee() -> Weight {
		Weight::from_parts(10_000_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

	fn delete_profile() -> Weight {
		Weight::from_parts(13_000_000, 1489)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

impl WeightInfo for () {
	fn create_profile() -> Weight {
		Weight::from_parts(14_000_000, 1600)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}

	fn update_metadata() -> Weight {
		Weight::from_parts(11_000_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}

	fn set_follow_fee() -> Weight {
		Weight::from_parts(10_000_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}

	fn delete_profile() -> Weight {
		Weight::from_parts(13_000_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
