//! Autogenerated weights for `pallet_social_managers`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-04-21, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `surfers-MacBook-Pro-2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/stack-template-runtime/stack_template_runtime.compact.compressed.wasm
// --pallet
// pallet_social_managers
// --extrinsic ""
// --steps 20
// --repeat 10
// --output target/benchmarks/pallet_social_managers.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame::{deps::frame_support::weights::constants::RocksDbWeight, prelude::*};
use core::marker::PhantomData;

/// Weight functions needed for pallet_social_managers.
pub trait WeightInfo {
	fn add_manager() -> Weight;
	fn remove_manager() -> Weight;
	fn remove_all_managers(n: u32) -> Weight;
	fn act_as_manager() -> Weight;
}

/// Weights for `pallet_social_managers` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `SocialManagers::ProfileManagers` (r:1 w:1)
	/// Storage: `SocialManagers::ManagerCount` (r:1 w:1)
	fn add_manager() -> Weight {
		// Measured: `456`  Estimated: `3584`  Min time: 12_000_000 ps.
		Weight::from_parts(13_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3584))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `SocialManagers::ProfileManagers` (r:1 w:1)
	/// Storage: `SocialManagers::ManagerCount` (r:1 w:1)
	fn remove_manager() -> Weight {
		// Measured: `291`  Estimated: `3584`  Min time: 9_000_000 ps.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3584))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `SocialManagers::ProfileManagers` (r:9 w:8)
	/// Storage: `SocialManagers::ManagerCount` (r:0 w:1)
	/// The range of component `n` is `[0, 8]`.
	fn remove_all_managers(n: u32) -> Weight {
		// Measured: `221 + n * 74`  Estimated: `3584 + n * 2594`  Min time: 6_000_000 ps.
		Weight::from_parts(7_561_856, 0)
			.saturating_add(Weight::from_parts(0, 3584))
			.saturating_add(Weight::from_parts(3_030_998, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2594).saturating_mul(n.into()))
	}
	/// Storage: `SocialManagers::ProfileManagers` (r:1 w:0)
	/// Storage: `SocialProfiles::Profiles` (r:1 w:0)
	fn act_as_manager() -> Weight {
		// Measured: `254`  Estimated: `3663`  Min time: 10_000_000 ps.
		Weight::from_parts(11_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3663))
			.saturating_add(T::DbWeight::get().reads(2))
	}
}

/// For backwards compatibility and tests.
impl WeightInfo for () {
	fn add_manager() -> Weight {
		Weight::from_parts(13_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3584))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn remove_manager() -> Weight {
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3584))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn remove_all_managers(n: u32) -> Weight {
		Weight::from_parts(7_561_856, 0)
			.saturating_add(Weight::from_parts(0, 3584))
			.saturating_add(Weight::from_parts(3_030_998, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(1))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2594).saturating_mul(n.into()))
	}
	fn act_as_manager() -> Weight {
		Weight::from_parts(11_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3663))
			.saturating_add(RocksDbWeight::get().reads(2))
	}
}
