//! Autogenerated weights for `pallet_sponsorship`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-04-21, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `surfers-MacBook-Pro-2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/stack-template-runtime/stack_template_runtime.compact.compressed.wasm
// --pallet
// pallet_sponsorship
// --extrinsic ""
// --steps 20
// --repeat 10
// --output target/benchmarks/pallet_sponsorship.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use core::marker::PhantomData;
use frame::{deps::frame_support::weights::constants::RocksDbWeight, prelude::*};

pub trait WeightInfo {
	fn register_beneficiary() -> Weight;
	fn revoke_beneficiary() -> Weight;
	fn revoke_my_sponsor() -> Weight;
	fn top_up() -> Weight;
	fn withdraw() -> Weight;
}

/// Weights for `pallet_sponsorship` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Sponsorship::SponsorOf` (r:1 w:1)
	/// Storage: `Sponsorship::BeneficiaryCount` (r:1 w:1)
	fn register_beneficiary() -> Weight {
		// Measured: `76`  Estimated: `3545`  Min time: 7_000_000 ps.
		Weight::from_parts(8_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3545))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Sponsorship::SponsorOf` (r:1 w:1)
	/// Storage: `Sponsorship::BeneficiaryCount` (r:1 w:1)
	fn revoke_beneficiary() -> Weight {
		// Measured: `256`  Estimated: `3545`  Min time: 9_000_000 ps.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3545))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Sponsorship::SponsorOf` (r:1 w:1)
	/// Storage: `Sponsorship::BeneficiaryCount` (r:1 w:1)
	fn revoke_my_sponsor() -> Weight {
		// Measured: `256`  Estimated: `3545`  Min time: 9_000_000 ps.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3545))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Storage: `Sponsorship::SponsorPots` (r:1 w:1)
	fn top_up() -> Weight {
		// Measured: `76`  Estimated: `3593`  Min time: 31_000_000 ps.
		Weight::from_parts(33_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Sponsorship::SponsorPots` (r:1 w:1)
	/// Storage: `System::Account` (r:1 w:1)
	fn withdraw() -> Weight {
		// Measured: `269`  Estimated: `3593`  Min time: 36_000_000 ps.
		Weight::from_parts(38_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}

impl WeightInfo for () {
	fn register_beneficiary() -> Weight {
		Weight::from_parts(8_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3545))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn revoke_beneficiary() -> Weight {
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3545))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn revoke_my_sponsor() -> Weight {
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3545))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn top_up() -> Weight {
		Weight::from_parts(33_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn withdraw() -> Weight {
		Weight::from_parts(38_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
}
