//! Autogenerated weights for `pallet-sponsorship`.
//!
//! **NOTE**: Placeholder estimates. Replace with output from
//! `frame-omni-bencher` against a production build of the runtime.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use core::marker::PhantomData;
use frame::{deps::frame_support::weights::constants::RocksDbWeight, prelude::*};

pub trait WeightInfo {
	fn register_beneficiary() -> Weight;
	fn revoke_beneficiary() -> Weight;
	fn revoke_my_sponsor() -> Weight;
	fn top_up() -> Weight;
	fn withdraw() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn register_beneficiary() -> Weight {
		Weight::from_parts(22_000_000, 2000)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn revoke_beneficiary() -> Weight {
		Weight::from_parts(18_000_000, 1800)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn revoke_my_sponsor() -> Weight {
		Weight::from_parts(16_000_000, 1800)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn top_up() -> Weight {
		Weight::from_parts(20_000_000, 1800)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn withdraw() -> Weight {
		Weight::from_parts(20_000_000, 1800)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

impl WeightInfo for () {
	fn register_beneficiary() -> Weight {
		Weight::from_parts(22_000_000, 2000)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn revoke_beneficiary() -> Weight {
		Weight::from_parts(18_000_000, 1800)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn revoke_my_sponsor() -> Weight {
		Weight::from_parts(16_000_000, 1800)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn top_up() -> Weight {
		Weight::from_parts(20_000_000, 1800)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn withdraw() -> Weight {
		Weight::from_parts(20_000_000, 1800)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
