//! Autogenerated weights for `pallet_social_feeds`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-04-21, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `surfers-MacBook-Pro-2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/stack-template-runtime/stack_template_runtime.compact.compressed.wasm
// --pallet
// pallet_social_feeds
// --extrinsic ""
// --steps 20
// --repeat 10
// --output target/benchmarks/pallet_social_feeds.rs
//
// `redact_post` was skipped by the bencher (`ModerationOrigin::try_successful_origin`
// returns `Err` until the runtime provides a benchmark-friendly guard); the
// values below for that method are conservative placeholders matching the
// previous hand-authored estimate.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame::{deps::frame_support::weights::constants::RocksDbWeight, prelude::*};
use core::marker::PhantomData;

/// Weight functions needed for pallet_social_feeds.
pub trait WeightInfo {
	fn create_post(n: u32) -> Weight;
	fn create_reply(n: u32) -> Weight;
	fn unlock_post() -> Weight;
	fn set_key_service() -> Weight;
	fn deliver_unlock_unsigned() -> Weight;
	fn redact_post() -> Weight;
}

/// Weights for `pallet_social_feeds` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// The range of component `n` is `[0, 9999]`.
	fn create_post(n: u32) -> Weight {
		// Measured: `290 + n * 8`  Estimated: `83515`  Min time: 49_000_000 ps.
		Weight::from_parts(57_414_370, 0)
			.saturating_add(Weight::from_parts(0, 83515))
			.saturating_add(Weight::from_parts(5_428, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// The range of component `n` is `[0, 9999]`.
	fn create_reply(n: u32) -> Weight {
		// Measured: `565 + n * 8`  Estimated: `83515`  Min time: 46_000_000 ps.
		Weight::from_parts(47_888_782, 0)
			.saturating_add(Weight::from_parts(0, 83515))
			.saturating_add(Weight::from_parts(5_407, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	fn unlock_post() -> Weight {
		// Measured: `494`  Estimated: `3818`  Min time: 42_000_000 ps.
		Weight::from_parts(44_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3818))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	fn set_key_service() -> Weight {
		// Measured: `98`  Estimated: `1553`  Min time: 4_000_000 ps.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1553))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn deliver_unlock_unsigned() -> Weight {
		// Hand-estimated: 1 read (Unlocks) + 2 writes (Unlocks, PendingUnlocks).
		// Cannot be benchmarked without a real OCW signature.
		Weight::from_parts(14_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	fn redact_post() -> Weight {
		// Placeholder — bencher skipped this call because the runtime
		// has no successful `ModerationOrigin` in benchmark mode.
		Weight::from_parts(11_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

/// For backwards compatibility and tests.
impl WeightInfo for () {
	fn create_post(n: u32) -> Weight {
		Weight::from_parts(57_414_370, 0)
			.saturating_add(Weight::from_parts(0, 83515))
			.saturating_add(Weight::from_parts(5_428, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(5))
	}
	fn create_reply(n: u32) -> Weight {
		Weight::from_parts(47_888_782, 0)
			.saturating_add(Weight::from_parts(0, 83515))
			.saturating_add(Weight::from_parts(5_407, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(6))
			.saturating_add(RocksDbWeight::get().writes(6))
	}
	fn unlock_post() -> Weight {
		Weight::from_parts(44_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3818))
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	fn set_key_service() -> Weight {
		Weight::from_parts(5_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1553))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn deliver_unlock_unsigned() -> Weight {
		Weight::from_parts(14_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn redact_post() -> Weight {
		Weight::from_parts(11_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}
