//! Autogenerated weights for pallet_social_feeds
//!
//! **NOTE**: These weights are placeholder estimates.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame::{deps::frame_support::weights::constants::RocksDbWeight, prelude::*};
use core::marker::PhantomData;

/// Weight functions needed for pallet_social_feeds.
pub trait WeightInfo {
	fn create_post() -> Weight;
	fn create_reply() -> Weight;
	fn unlock_post() -> Weight;
}

/// Weights for pallet_social_feeds using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn create_post() -> Weight {
		Weight::from_parts(20_000_000, 2000)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}

	fn create_reply() -> Weight {
		Weight::from_parts(25_000_000, 2500)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}

	fn unlock_post() -> Weight {
		Weight::from_parts(15_000_000, 1600)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

/// For backwards compatibility and tests.
impl WeightInfo for () {
	fn create_post() -> Weight {
		Weight::from_parts(20_000_000, 2000)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}

	fn create_reply() -> Weight {
		Weight::from_parts(25_000_000, 2500)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}

	fn unlock_post() -> Weight {
		Weight::from_parts(15_000_000, 1600)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
