//! Autogenerated weights for `pallet_social_graph`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-04-21, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `surfers-MacBook-Pro-2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/stack-template-runtime/stack_template_runtime.compact.compressed.wasm
// --pallet
// pallet_social_graph
// --extrinsic ""
// --steps 20
// --repeat 10
// --output target/benchmarks/pallet_social_graph.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame::{deps::frame_support::weights::constants::RocksDbWeight, prelude::*};
use core::marker::PhantomData;

/// Weight functions needed for pallet_social_graph.
pub trait WeightInfo {
	fn follow() -> Weight;
	fn unfollow() -> Weight;
}

/// Weights for `pallet_social_graph` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `SocialProfiles::Profiles` (r:2 w:0)
	/// Storage: `SocialGraph::Follows` (r:1 w:1)
	/// Storage: `SocialGraph::FollowerCount` (r:1 w:1)
	/// Storage: `SocialGraph::FollowingCount` (r:1 w:1)
	fn follow() -> Weight {
		// Measured: `182`  Estimated: `6336`  Min time: 16_000_000 ps.
		Weight::from_parts(17_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6336))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `SocialGraph::Follows` (r:1 w:1)
	/// Storage: `SocialGraph::FollowerCount` (r:1 w:1)
	/// Storage: `SocialGraph::FollowingCount` (r:1 w:1)
	fn unfollow() -> Weight {
		// Measured: `277`  Estimated: `3565`  Min time: 12_000_000 ps.
		Weight::from_parts(14_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3565))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}

/// For backwards compatibility and tests.
impl WeightInfo for () {
	fn follow() -> Weight {
		Weight::from_parts(17_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6336))
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	fn unfollow() -> Weight {
		Weight::from_parts(14_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3565))
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
}
