//! Autogenerated weights for pallet_social_graph
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-04-14
//!
//! **NOTE**: These weights are placeholder estimates. Run benchmarks on your own hardware for
//! accurate production values.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame::{deps::frame_support::weights::constants::RocksDbWeight, prelude::*};
use core::marker::PhantomData;

/// Weight functions needed for pallet_social_graph.
pub trait WeightInfo {
	fn follow() -> Weight;
	fn unfollow() -> Weight;
}

/// Weights for pallet_social_graph using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `SocialGraph::Follows` (r:1 w:1)
	/// Storage: `SocialGraph::FollowerCount` (r:1 w:1)
	/// Storage: `SocialGraph::FollowingCount` (r:1 w:1)
	fn follow() -> Weight {
		Weight::from_parts(18_000_000, 1800)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}

	/// Storage: `SocialGraph::Follows` (r:1 w:1)
	/// Storage: `SocialGraph::FollowerCount` (r:1 w:1)
	/// Storage: `SocialGraph::FollowingCount` (r:1 w:1)
	fn unfollow() -> Weight {
		Weight::from_parts(15_000_000, 1600)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

/// For backwards compatibility and tests.
impl WeightInfo for () {
	fn follow() -> Weight {
		Weight::from_parts(18_000_000, 1800)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}

	fn unfollow() -> Weight {
		Weight::from_parts(15_000_000, 1600)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}
